<?php

namespace Vifeed\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Vifeed\CampaignBundle\Entity\Campaign;
use Vifeed\PlatformBundle\Entity\CampaignBan;
use Vifeed\PlatformBundle\Entity\Platform;

/**
 * CampaignBanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignBanRepository extends EntityRepository
{
    /**
     * @param Platform $platform
     *
     * @return Campaign[]
     */
    public function findBannedCampaignsByPlatfrom(Platform $platform)
    {
        /** @var CampaignBan[] $bans */
        $bans = $this->findByPlatform($platform);

        $campaigns = [];
        foreach ($bans as $ban) {
            $campaigns[$ban->getCampaign()->getId()] = $ban->getCampaign();
        }

        return $campaigns;
    }


}
