payment:
    type: rest
    resource: '@VifeedPaymentBundle/Controller/Api/PaymentController.php'
    name_prefix: api_

withdrawal:
    type: rest
    resource: '@VifeedPaymentBundle/Controller/Api/WithdrawalController.php'
    name_prefix: api_

wallet:
    type: rest
    resource: '@VifeedPaymentBundle/Controller/Api/WalletController.php'
    name_prefix: api_

