parameters:
    payment.form.my_payment_type.class: Vifeed\PaymentBundle\Form\MyPaymentType
    payment.plugin.my.class: Vifeed\PaymentBundle\Plugin\MyPlugin

services:
#    payment.form.my_payment_type:
#        class: %payment.form.my_payment_type.class%
#        tags:
#            - { name: "payment.method_form_type" }
#            - { name: "form.type", alias: "my_payment_type" }
#
#    payment.plugin.my:
#        class: %payment.plugin.my.class%
#        tags:
#            - { name: "payment.plugin" }

    payment.state.change.listener:
            class:  Vifeed\PaymentBundle\EventListener\PaymentStateChangeListener
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: 'kernel.event_subscriber' }
