<?php

namespace Vifeed\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @return User[]
     */
    public function findPartnersForNotification()
    {
        $qb = $this->createQueryBuilder('u');
        $qb->where('u.type = :type')
           ->andWhere('u.notification > 0')
           ->andWhere(($qb->expr()->eq('u.enabled', $qb->expr()->literal(true))))
           ->setParameter('type', User::TYPE_PUBLISHER);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param User $user
     * @param      $value
     */
    public function updateBalance(User $user, $value)
    {
        $qb = $this->createQueryBuilder('u')
                   ->update('Vifeed\UserBundle\Entity\User', 'u')
                   ->set('u.balance', 'u.balance + :value')
                   ->where('u = :user')
                   ->setParameters([
                                         'user'  => $user,
                                         'value' => $value
                                   ]);
        $qb->getQuery()->execute();
    }

}
