language: php

php:
  - 5.4

services:
  - redis-server

before_script: composer install -n

script:
  - phpunit -c app --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="2087e8c79ea31fd94006200b4885c35ae54067c19d477ccc1f8d584de6f35876" --format=php-clover coverage.clover

after_failure:
  - echo log file; cat app/logs/test.log

notifications:
  flowdock: 99c0b1ff68ca7ff45786742d6430d6a7
