language: php

php:
  - 5.4

services:
  - redis-server

before_script: composer install -n

script:
  - phpunit -c app
  - phpunit -c app --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="3b8677744441f35d1071445244f1e9c503fdb49626da5ce3b819bc11dfe6f1c9" --format=php-clover coverage.clover

after_failure:
  - echo log file; cat app/logs/test.log

notifications:
  flowdock: 99c0b1ff68ca7ff45786742d6430d6a7
