language: php

php:
  - 5.5

services:
  - redis-server

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('rootpass') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer install -n

script:
  - phpunit -c app vendor/vifeed/
  - phpunit -c app --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="code" --format=php-clover coverage.clover
  - php ./app/console doctrine:migrations:migrate 20140123131601 --env=test --no-interaction

after_failure:
  - echo log file; cat app/logs/test.log

after_success:
  - sh travis/deploy.sh
#  - php travis/deploy.php

notifications:
  flowdock: code

source_key: code=
