parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: vifeed
    database_user: root
    database_password: rootpass
    mailer_transport: gmail
    mailer_host: null
    mailer_user: hd.deman@gmail.com
    mailer_password: huy
    locale: ru
    secret: aydiAQgxzRECfg9raqVD4fzPaYcFGxrpCFGXHRWarMjFA38EspxdBdVod
    developer_email: dev@example.com
    assetic.filter.compass.images_dir: '%kernel.root_dir%/../web/'
    assetic.filter.compass.http_path: /
    assetic.filter.compass.generated_images_path: '%kernel.root_dir%/../web/images/'
    assetic.cdn_url: 'http://vifeed.co'
    assetic.cdn_path: '%kernel.root_dir%/../web'
    social: { VKAppID: '', VKAppSecret: '' }
    assetic.filter.compass.bin: /usr/local/bin/compass
    payment.secret: 2ceea4871a6205c421dc3ce9b0a7b350aafe7000
    robokassa.login: 2ceea4871a6205c421dc3ce9b0a7b350aafe7000
    robokassa.password1: DZ1oZrZc9U8e
    robokassa.password2: dEv56kZLMA2X