<?php

namespace Vifeed\CampaignBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * Поиск тегов по названию или его части с начала
     *
     * @param string $word
     *
     * @return Tag[]
     */
    public function findByWord($word)
    {
        $tags = $this->createQueryBuilder('t')
              ->where('t.name LIKE :word')
              ->setParameter('word', $word . '%')
              ->getQuery()
              ->getResult();

        return $tags;
    }
}
