imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:  raven
            dsn:  https://6269461d6540477c86824631f7758762:268ddc43168440a5a76e75addd09c435@app.getsentry.com/17730
            level: notice
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: warning
