imports:
    - { resource: config.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    delivery_address:  %developer_email%

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: info

doctrine:
    dbal:
        dbname:   %database_name%_test

karser_robokassa:
    test: true