imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_base_urls:
            http: [%assetic.cdn_url%]
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id: snc_redis.session.handler
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    globals:
        social: %social%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ VifeedUserBundle, VifeedFrontendBundle ]
    #java: /usr/bin/java
    filters:
        sass: ~
        compass:
            apply_to: "\.(sass|scss)$"
            bin: %assetic.filter.compass.bin%
        cssrewrite:
            apply_to: "\.scss$"
        closure:
            jar: %kernel.root_dir%/Resources/java/compiler-latest/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
    read_from:        %assetic.cdn_url%
    write_to:         %assetic.cdn_path%
    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../bower-vendor/jquery/jquery.min.js
        jquery_parallax:
            inputs:
                - %kernel.root_dir%/../bower-vendor/parallax/deploy/jquery.parallax.min.js
        angular:
            inputs:
                - %kernel.root_dir%/../bower-vendor/angular/angular.js
                - %kernel.root_dir%/../bower-vendor/angular-route/angular-route.min.js
                - %kernel.root_dir%/../bower-vendor/angular-resource/angular-resource.min.js
                - %kernel.root_dir%/../bower-vendor/angular-sanitize/angular-sanitize.min.js
                # - %kernel.root_dir%/../bower-vendor/angular-mocks/angular-mocks.js
        twitter_bootstrap_js:
            inputs:
                - %kernel.root_dir%/../bower-vendor/bootstrap-sass/js/carousel.js
                - %kernel.root_dir%/../bower-vendor/bootstrap-sass/js/dropdown.js
        #Angular UI ~ Bootstrap
        #http://angular-ui.github.io/bootstrap/
        #https://github.com/angular-ui/bootstrap/
        angular_ui_bootstrap:
            inputs:
                #tabs
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/tabs/tabs.js
                - %kernel.root_dir%/../tmp/angular-ui-tabs-templates.js
                #modal
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/modal/modal.js
                - %kernel.root_dir%/../tmp/angular-ui-modal-templates.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/transition/transition.js
                #popover and tooltip
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/popover/popover.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/tooltip/tooltip.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/position/position.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/bindHtml/bindHtml.js
                #alert
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/alert/alert.js
        crypto_js:
            inputs:
                - %kernel.root_dir%/../bower-vendor/crypto-js/components/core-min.js
                - %kernel.root_dir%/../bower-vendor/crypto-js/components/sha1-min.js
                - %kernel.root_dir%/../bower-vendor/crypto-js/components/md5-min.js
                - %kernel.root_dir%/../bower-vendor/crypto-js/components/enc-base64-min.js
        angularjs_cookies:
            inputs:
                - %kernel.root_dir%/../bower-vendor/xapu-angular-cookies/cookiesModule.js
        angular_ui:
            inputs:
                - %kernel.root_dir%/../vendor/angular-ui/ui-utils/modules/mask/mask.js
                - %kernel.root_dir%/../bower-vendor/angular-ui-select2/src/select2.js
        jquery_widget_select2_js:
            inputs:
                - %kernel.root_dir%/../bower-vendor/select2/select2.min.js
                - %kernel.root_dir%/../bower-vendor/select2/select2_locale_ru.js
        select2_css:
            inputs:
                - %kernel.root_dir%/../bower-vendor/select2/select2.css
        ng_progress:
            inputs:
                - %kernel.root_dir%/../bower-vendor/ngprogress-lite/ngprogress-lite.min.js
        ng_progress_css:
            inputs:
                - %kernel.root_dir%/../bower-vendor/ngprogress-lite/ngprogress-lite.css
        fos_js_routes:
            inputs:
                - @FOSJsRoutingBundle/Resources/public/js/router.js
                - %kernel.root_dir%/../web/js/fos_js_routes.js
            filters:
                - ?closure
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
        type: service
        id: snc_redis.swiftmailer.spool

fos_rest:
    routing_loader:
        default_format: json
    view:
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    param_fetcher_listener: force
    serializer:
            serialize_null: true
#    format_listener:
#        rules:
#            - { path: '^/', fallback_format: json, prefer_extension: false }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Vifeed\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled:    true
            template:   VifeedUserBundle:Registration:email.html.twig

nelmio_api_doc: ~

snc_redis:
    session:
        client: session
        ttl: 7200
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dns.default%
        session:
            type: predis
            alias: session
            dsn: %redis_dns.session%
    swiftmailer:
        client: default
        key: swiftmailer

jms_payment_core:
    secret: %payment.secret%

karser_robokassa:
    login: %robokassa.login%
    password1: %robokassa.password1%
    password2: %robokassa.password2%
    test: false

cayetanosoriano_hashids:
    salt: %cayetanosoriano_hashids.salt%
    min_hash_length: %cayetanosoriano_hashids.min_hash_length%
