imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        api: auto
        enable_annotations: true
    templating:
        engines: ['twig']
        assets_base_urls:
            http: [%assetic.cdn_url%]
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: snc_redis.session.handler
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    globals:
        social: %social%
        tracker_host: %tracker.host%
        cdn_url: %assetic.cdn_url%
        backend_host: %backend.host%
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [VifeedUserBundle, VifeedFrontendBundle, VifeedVideoPromoBundle]
    ruby:  %assetic.ruby.bin%
    filters:
        sass: ~
        compass:
            apply_to: "\.(sass|scss)$"
            bin: %assetic.filter.compass.bin%
        cssrewrite:
            apply_to: "\.scss$"
        closure:
            jar: %kernel.root_dir%/Resources/java/compiler-latest/compiler.jar
            apply_to: "\.coffee$"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        coffee:
            bin: %kernel.root_dir%/../node_modules/.bin/coffee
            node: /usr/local/bin/node
            apply_to: "\.coffee$"
    read_from:        %assetic.cdn_url%
    write_to:         %assetic.cdn_path%
    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../bower-vendor/jquery/dist/jquery.min.js
        jquery_parallax:
            inputs:
                - %kernel.root_dir%/../bower-vendor/parallax/deploy/jquery.parallax.min.js
        jquery_easy_pie_chart:
            inputs:
                - %kernel.root_dir%/../bower-vendor/jquery.easy-pie-chart/dist/jquery.easypiechart.min.js
        skrollr:
            inputs:
                - %kernel.root_dir%/../bower-vendor/skrollr/dist/skrollr.min.js
        angular:
            inputs:
                - %kernel.root_dir%/../bower-vendor/angular/angular.min.js
                - %kernel.root_dir%/../bower-vendor/angular-route/angular-route.min.js
                - %kernel.root_dir%/../bower-vendor/angular-resource/angular-resource.min.js
                - %kernel.root_dir%/../bower-vendor/angular-sanitize/angular-sanitize.min.js
                - %kernel.root_dir%/../bower-vendor/angular-mocks/angular-mocks.js
        twitter_bootstrap_js:
            inputs:
                # - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/affix.js
                # - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/alert.js
                # - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/button.js
                - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/carousel.js
                - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/collapse.js
                - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/dropdown.js
                # - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/tab.js
                - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/transition.js
                # - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/scrollspy.js
                # - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/modal.js
                # - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/tooltip.js
                # - %kernel.root_dir%/../bower-vendor/bootstrap-sass-twbs/vendor/assets/javascripts/bootstrap/popover.js
            filters:
                - ?closure
        #Angular UI ~ Bootstrap
        #http://angular-ui.github.io/bootstrap/
        #https://github.com/angular-ui/bootstrap/
        angular_ui_bootstrap:
            inputs:
                #tabs
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/tabs/tabs.js
                - %kernel.root_dir%/../tmp/angular-ui-tabs-templates.js
                #modal
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/modal/modal.js
                - %kernel.root_dir%/../tmp/angular-ui-modal-templates.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/transition/transition.js
                #other bootstrap directives
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/popover/popover.js
                - %kernel.root_dir%/../tmp/angular-ui-popover-templates.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/tooltip/tooltip.js
                - %kernel.root_dir%/../tmp/angular-ui-tooltip-templates.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/position/position.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/bindHtml/bindHtml.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/alert/alert.js
                - %kernel.root_dir%/../tmp/angular-ui-alert-templates.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/dropdown/dropdown.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/pagination/pagination.js
                - %kernel.root_dir%/../tmp/angular-ui-pagination-templates.js
                - %kernel.root_dir%/../vendor/angular-ui/bootstrap/src/buttons/buttons.js
            filters:
                - ?closure
        angular_maps:
            inputs:
                - %kernel.root_dir%/../bower-vendor/angular-google-maps/dist/angular-google-maps.min.js
        crypto_js:
            inputs:
                - %kernel.root_dir%/../bower-vendor/crypto-js/components/core-min.js
                - %kernel.root_dir%/../bower-vendor/crypto-js/components/sha1-min.js
                - %kernel.root_dir%/../bower-vendor/crypto-js/components/md5-min.js
                - %kernel.root_dir%/../bower-vendor/crypto-js/components/enc-base64-min.js
        angularjs_cookies:
            inputs:
                - %kernel.root_dir%/../bower-vendor/xapu-angular-cookies/cookiesModule.js
        angular_ui:
            inputs:
                - %kernel.root_dir%/../vendor/angular-ui/ui-utils/modules/mask/mask.js
                - %kernel.root_dir%/../vendor/angular-ui/ui-utils/modules/event/event.js
            filters:
                - ?closure
        angular_socket:
            inputs:
                - %kernel.root_dir%/../bower-vendor/angular-socket-io/socket.min.js
        lodash:
            inputs:
                - %kernel.root_dir%/../bower-vendor/lodash/dist/lodash.underscore.min.js
        frontend_config:
            inputs:
                - %kernel.root_dir%/../tmp/frontend_config.js
            filters:
                - ?closure
        select2_js:
            inputs:
                - %kernel.root_dir%/../bower-vendor/select2/select2.min.js
                - %kernel.root_dir%/../bower-vendor/select2/select2_locale_ru.js
                - %kernel.root_dir%/../bower-vendor/angular-ui-select2/src/select2.js
            filters:
                - ?closure
        select2_css:
            inputs:
                - %kernel.root_dir%/../bower-vendor/select2/select2.css
        ng_progress:
            inputs:
                - %kernel.root_dir%/../bower-vendor/ngprogress-lite/ngprogress-lite.min.js
        ng_progress_css:
            inputs:
                - %kernel.root_dir%/../bower-vendor/ngprogress-lite/ngprogress-lite.css
        ladda_bootstrap:
            inputs:
                - %kernel.root_dir%/../bower-vendor/ladda-bootstrap/dist/spin.min.js
                - %kernel.root_dir%/../bower-vendor/ladda-bootstrap/dist/ladda.min.js
        ladda_bootstrap_css:
            inputs:
                - %kernel.root_dir%/../bower-vendor/ladda-bootstrap/dist/ladda-themeless.min.css
        moment_js:
            inputs:
                - %kernel.root_dir%/../bower-vendor/moment/min/moment-with-locales.min.js
                - %kernel.root_dir%/../bower-vendor/twix/bin/twix.min.js
                - %kernel.root_dir%/../bower-vendor/angular-moment/angular-moment.min.js
        daterangepicker:
            inputs:
                - %kernel.root_dir%/../bower-vendor/bootstrap-daterangepicker/daterangepicker.js
            filters:
                - ?closure
        daterangepicker_css:
            inputs:
                - %kernel.root_dir%/../bower-vendor/bootstrap-daterangepicker/daterangepicker-bs3.css
        highcharts:
            inputs:
                - %kernel.root_dir%/../bower-vendor/highcharts-release/highcharts.js
                - %kernel.root_dir%/../bower-vendor/highcharts-ng/dist/highcharts-ng.min.js
            filters:
                - ?closure
        analytics_template:
            inputs:
                - %kernel.root_dir%/../tmp/analytics-templates.js
            filters:
                - ?closure
        advertiser_template:
            inputs:
                - %kernel.root_dir%/../tmp/advertiser-templates.js
            filters:
                - ?closure
        profile_template:
            inputs:
                - %kernel.root_dir%/../tmp/profile-templates.js
            filters:
                - ?closure
        publisher_template:
            inputs:
                - %kernel.root_dir%/../tmp/publisher-templates.js
            filters:
                - ?closure
        security_template:
            inputs:
                - %kernel.root_dir%/../tmp/security-templates.js
            filters:
                - ?closure
        sexy_modal_template:
            inputs:
                - %kernel.root_dir%/../tmp/sexy-modal-templates.js
            filters:
                - ?closure
        fos_js_routes:
            inputs:
                - @FOSJsRoutingBundle/Resources/public/js/router.js
                - %kernel.root_dir%/../web/js/fos_js_routes.js
            filters:
                - ?closure
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            datetime_functions:
                from_unixtime: Vifeed\SystemBundle\DQL\FromUnixtimeFunction
                date_format: Vifeed\SystemBundle\DQL\DateFormatFunction
        result_cache_driver: redis
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: %mailer_encryption%
    spool:
        type: service
        id: snc_redis.swiftmailer.spool

fos_rest:
    routing_loader:
        default_format: json
    view:
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    param_fetcher_listener: force
    serializer:
            serialize_null: true
#    format_listener:
#        rules:
#            - { path: '^/', fallback_format: json, prefer_extension: false }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Vifeed\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled:    true
            template:   VifeedUserBundle:Registration:email.html.twig
    resetting:
         form:
             type: resetting
             name: resetting
    from_email:
        address: no-reply@zombakka.com
        sender_name: zombakka

nelmio_api_doc: ~

snc_redis:
    session:
        client: session
        ttl: 7200
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dns.default%
        session:
            type: predis
            alias: session
            dsn: %redis_dns.session%
        doctrine:
            type: predis
            alias: doctrine
            dsn: %redis_dns.doctrine%
    swiftmailer:
        client: default
        key: swiftmailer
    doctrine:
#        metadata_cache:
#            client: doctrine
#            entity_manager: default          # the name of your entity_manager connection
#            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: doctrine
            entity_manager: default  # you may specify multiple entity_managers
#        query_cache:
#            client: doctrine
#            entity_manager: default

jms_payment_core:
    secret: %payment.secret%

karser_robokassa:
    login: %robokassa.login%
    password1: %robokassa.password1%
    password2: %robokassa.password2%
    test: false

chewbacco_payment_qiwi_wallet:
    login: %qiwi.login%
    password: %qiwi.password%

jms_payment_paypal:
    username: %paypal.username%
    password: %paypal.password%
    signature: %paypal.api_signature%
    debug: false

vresh_twilio:
    sid: %twilio.sid%
    authToken: %twilio.token%

cayetanosoriano_hashids:
    salt: %cayetanosoriano_hashids.salt%
    min_hash_length: %cayetanosoriano_hashids.min_hash_length%

old_sound_rabbit_mq:
    connections:
        default:
            host:     %rabbitmq.host%
            port:     %rabbitmq.port%
            user:     %rabbitmq.user%
            password: %rabbitmq.password%
            vhost:    %rabbitmq.vhost%
            lazy:     true
    producers:
        video_view:
            connection:       default
            exchange_options: {name: 'video-view', type: direct}
            queue_options:    {name: 'video-view-payment'}
        campaign_status_change:
            connection:       default
            exchange_options: {name: 'campaign-change', type: direct}
            queue_options:    {name: 'new-campaign'}
    consumers:
        new_campaign_notify:
            connection:       default
            exchange_options: {name: 'campaign-change', type: direct}
            queue_options:    {name: 'new-campaign'}
            callback:         vifeed.rabbit.new_campaign_notify.consumer
        pay_video_view:
            exchange_options: {name: 'video-view', type: direct}
            queue_options:    {name: 'video-view-payment'}
            qos_options:      {prefetch_size: 0, prefetch_count: 3, global: false}
            callback:         vifeed.payment.pay_video_view.consumer

stof_doctrine_extensions:
    default_locale: ru_RU
    orm:
        default:
            softdeleteable: true
            timestampable: true

bank_payment:
    templates:
        receipt: ::receipt.html.twig
        transfer: ::transfer.html.twig

