# чтобы тесты проходили независимо от изменяющихся параметров, зафиксируем отдельные параметры для тестов
parameters:
    vifeed:
        comission: 0.3
        min_view_time: 30
        delta: 1
        company_name: 'ООО "Вифид"'
        inn: '12345668'
        bank_name: 'Банк'
        corr_number: '12345'
        bik: '21245436'
        account_number: '12121212121'
        bank_account_nubmer: '121212121' # оно надо?
        kpp: '12121212121'
        short_video_duration: 5
    vifeed.ip_filter.short_skip_time: 600
    vifeed.ip_filter.long_skip_time: 86400
    vifeed.ip_filter.long_skip_views: 5
    vifeed.ip_filter.timeout_per_campaign: 0
    vifeed.min_balance_for_sms: 100
