parameters:
    project.environment: stage
    database_driver: pdo_mysql
    database_host: host
    database_port: null
    database_name: vifeed
    database_user: chief
    database_password: pass
    mailer_transport: smtp
    mailer_encryption: tls
    mailer_host: code
    mailer_user: code
    mailer_password: code
    locale: ru
    secret: 'code'
    developer_email: no-reply@zombakka.com
    assetic.ruby.bin: /opt/rbenv/versions/2.1.2/bin/ruby
    assetic.filter.compass.bin: /opt/rbenv/versions/2.1.2/bin/compass
    assetic.filter.compass.images_dir: '%kernel.root_dir%/../web/'
    assetic.filter.compass.http_path: /
    assetic.filter.compass.http_generated_images_path: /
    assetic.filter.compass.generated_images_path: '%kernel.root_dir%/../web/'
    assetic.filter.compass.timeout: 600
    assetic.cdn_url: 'http://cdn-stage.vifeed.co'
    assetic.cdn_path: "%kernel.root_dir%/../web"
    social: { VKAppID: code, VKAppSecret: '' }
    payment.secret: code
    robokassa.login: code
    robokassa.password1: code
    robokassa.password2: code
    redis_dns.default: 'code'
    redis_dns.session: 'code'
    redis_dns.doctrine: 'code'
    cayetanosoriano_hashids.salt: 'code'
    cayetanosoriano_hashids.min_hash_length: 6
    google.api.key: 'code'
    qiwi.login: code
    qiwi.password: 'code'
    paypal.username: hd.deman@gmail.co
    paypal.password: weeqw
    paypal.api_signature: dsfsdf
    tracker.host: 'tracker-stage.vifeed.co'
    vifeed:
        comission: 0.5
        min_view_time: 6
        short_video_duration: 5
        delta: 1
        company_name: 'ООО «Бинго Студио»'
        inn: '7715923440'
        bank_name: '«Промсвязьбанк» (ОАО) Г. МОСКВА'
        corr_number: '30101810400000000555'
        bik: '044525555'
        account_number: '40702810500000016898'
        bank_account_nubmer: ''
        kpp: '771501001'
    vifeed.ip_filter.short_skip_time: 600
    vifeed.ip_filter.long_skip_time: 86400
    vifeed.ip_filter.long_skip_views: 5
    vifeed.ip_filter.timeout_per_campaign: 0
    vifeed.payment.max_workers: 2
    vifeed.min_balance_for_sms: 0
    feedback.notification.email: feedback@zombakka.com
    partnership.notification.email: partnership@zombakka.com
    withdrawal.notification.email: withdrawal@zombakka.com
    backend.host: backend.zombakka.com
    rabbitmq.host: 'hot-giraffe.rmq.cloudamqp.com'
    rabbitmq.port: 5672
    rabbitmq.user: 'code'
    rabbitmq.password: 'code'
    rabbitmq.vhost: 'stage'
    daemon.pid_file_location: /tmp
    twilio.sid: code
    twilio.token: code
    twilio.phone_number: code
    public_domain: vifeed.co
    promo_domain: zomba.me
    facebook.app_id: code
    facebook.app_secret: code
    vk.app_id: code
    vk.app_secret: code
