# чтобы тесты проходили независимо от изменяющихся параметров, зафиксируем отдельные параметры для тестов
parameters:
    vifeed:
        comission: 0.3
        min_view_time: 30
        delta: 1
        company_name: 'ООО "Вифид"'
        inn: '12345668'
        bank_name: 'Банк'
        corr_number: '12345'
        bik: '21245436'
        account_number: '12121212121'
        bank_account_nubmer: '121212121' # оно надо?
        kpp: '12121212121'
        short_video_duration: 5
        ip_filter:
            short_skip_time: 600
            long_skip_time: 86400
            long_skip_views: 5