rest:
  resource: routing_rest.yml
  prefix: /api

vifeed_public:
  resource: "@VifeedFrontendBundle/Resources/config/routing.yml"
  prefix: /

vifeed_payment:
  resource: "@VifeedPaymentBundle/Resources/config/routing.yml"
  prefix: /

vifeed_video_promo:
  resource: "@VifeedVideoPromoBundle/Resources/config/routing.yml"
  prefix: /
  host: "{domain}"
  requirements:
    domain: zomba.me|videos.vifeed.dev|videos.vifeed.co

default:
  pattern: /
  defaults:
    _controller: 'VifeedSystemBundle:Default:index'

vifeed_user_frontend:
  resource: "@VifeedUserBundle/Resources/config/routing_frontend.yml"
  prefix: /

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
