campaign_rest:
  type: rest
  resource: "@VifeedCampaignBundle/Resources/config/routing_rest.yml"
  prefix: /api

users_rest:
  type: rest
  resource: "@VifeedUserBundle/Resources/config/routing_rest.yml"
  prefix: /api

