rest:
  resource: routing_rest.yml
  prefix: /api

vifeed_public:
  resource: "@VifeedFrontendBundle/Resources/config/routing.yml"
  prefix: /
  host: "{domain}"
  requirements:
    domain: zombakka.com|vifeed.dev|vifeed.co|.*.vagrantshare.com
  defaults:
    domain: %public_domain%

vifeed_frontend_mirror:
  pattern:  /
  defaults: { _controller: VifeedFrontendBundle:Default:mirror }
  host: "{domain}"
  requirements:
    domain: www.zombakka.ru|www.zombakka.com|www.zombaka.ru|www.zombaka.com|zombakka.ru|zombaka.ru zombaka.com|www.zomba.me|zomba.me|videos.vifeed.co|videos.vifeed.dev

vifeed_payment:
  resource: "@VifeedPaymentBundle/Resources/config/routing.yml"
  prefix: /

vifeed_video_promo:
  resource: "@VifeedVideoPromoBundle/Resources/config/routing.yml"
  prefix: /
  host: "{domain}"
  requirements:
    domain: zomba.me|videos.vifeed.dev|videos.vifeed.co

default:
  pattern: /
  defaults:
    _controller: 'VifeedSystemBundle:Default:index'

vifeed_user_frontend:
  resource: "@VifeedUserBundle/Resources/config/routing_frontend.yml"
  prefix: /

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

nelmio_security:
    path:     /csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
    methods:  [POST]
