rest:
  resource: routing_rest.yml
  prefix: /api

vifeed_public:
    resource: "@VifeedPublicBundle/Resources/config/routing.yml"
    prefix:   /

default:
  pattern: /
  defaults:
    _controller: 'VifeedSystemBundle:Default:index'

users_frontend:
  resource: "@VifeedUserBundle/Resources/config/routing_frontend.yml"
  prefix: /user

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"