campaign_rest:
  type: rest
  resource: "@VifeedCampaignBundle/Resources/config/routing_rest.yml"

platform_rest:
  type: rest
  resource: "@VifeedPlatformBundle/Resources/config/routing_rest.yml"

users_rest:
  type: rest
  resource: "@VifeedUserBundle/Resources/config/routing_rest.yml"

payments_rest:
  type: rest
  resource: "@VifeedPaymentBundle/Resources/config/routing_rest.yml"

system_rest:
  type: rest
  resource: "@VifeedSystemBundle/Resources/config/routing_rest.yml"

geo_rest:
  type: rest
  resource: "@VifeedGeoBundle/Resources/config/routing_rest.yml"

tag_rest:
  type: rest
  resource: "@VifeedTagBundle/Resources/config/routing_rest.yml"

frontend_rest:
  type: rest
  resource: "@VifeedFrontendBundle/Resources/config/routing_rest.yml"