rest:
  resource: routing_rest.yml
  prefix: /api

users:
  resource: "@VifeedUserBundle/Resources/config/routing.yml"

default:
  pattern: /
  defaults:
    _controller: 'VifeedSystemBundle:default:index'