security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        wsse_secured:
            pattern:   ^/api/(?!(users$|user/login_check$|users/confirm$))
            stateless: true
            wsse:      true

        main:
            pattern: ^/
#            pattern: ^/(?!api)
            form_login:
                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
                check_path: /api/user/login_check
                success_handler: vifeed.security.authentication.success_handler
                failure_handler: vifeed.security.authentication.failure_handler
                require_previous_session: false
            logout:       true
            anonymous:    true



        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/users$, role: IS_AUTHENTICATED_ANONYMOUSLY } # регистрация
            - { path: ^/api/users/confirm$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/user/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#            - { path: ^/api/user/(register|login), role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/, role: ROLE_USER }

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
