security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        wsse_secured:
            pattern:   ^/api/(?!user)
            stateless: true
            wsse:      true

        main:
            pattern: ^/
#            pattern: ^/(?!api)
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /login_check
#                check_path: /api/user/login_check
#                default_target_path: /api/user/login_success
            logout:       true
            anonymous:    true

#        pre_auth:
#            pattern:  ^/api/user/(register|login)
#            security: false
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider



        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/user/(register|login), role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/, role: ROLE_USER }
#            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
