security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:

        wsse_secured:
            # ?! - просмотр вперёд с отрицанием
            # под паттерн попадают все урлы, кроме /api/users, /api/users/login_check, /api/users/confirm, /api/users/reset, api/partnership
            pattern:   ^/api/(?!(users(|/login_check|/confirm|/reset)|partnership)$)
            stateless: true
            wsse:      true

        main:
            pattern: ^/
#            pattern: ^/(?!api)
            form_login:
                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
                check_path: /api/users/login_check
                success_handler: vifeed.security.authentication.success_handler
                failure_handler: vifeed.security.authentication.failure_handler
                require_previous_session: false
            logout:       true
            anonymous:    true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/partnership$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/users$, role: IS_AUTHENTICATED_ANONYMOUSLY } # регистрация
            - { path: ^/api/users/confirm$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/users/reset$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/users/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/, role: ROLE_USER }