<?php

namespace Vifeed\PaymentBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Vifeed\PaymentBundle\Entity\Order;
use Vifeed\UserBundle\Entity\User;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{

    /**
     * @param \Vifeed\UserBundle\Entity\User $user
     * @param \DateTime                      $dateFrom
     * @param \DateTime                      $dateTo
     *
     * @return array
     */
    public function getPaymentStats(User $user, \DateTime $dateFrom, \DateTime $dateTo)
    {
        $qb = $this->createQueryBuilder('p');
        $query = $qb->select('p')
                    ->addSelect('i.paymentSystemName')
                    ->join('p.paymentInstruction', 'i')
                    ->where('p.user = :user')
                    ->andWhere('p.createdAt BETWEEN :date_from AND :date_to')
                    ->andWhere('p.status = :status')
                    ->orderBy('p.createdAt');
        $query->setParameters(
              ['user'      => $user,
               'date_from' => $dateFrom,
               'date_to'   => $dateTo,
               'status'    => Order::STATUS_PAID]
        );

        $payments = $query->getQuery()->getResult();

        return $payments;
    }


}
