<?php

namespace Vifeed\PaymentBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use Vifeed\PaymentBundle\Entity\Withdrawal;
use Vifeed\UserBundle\Entity\User;

/**
 * WalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WalletRepository extends EntityRepository
{

    /**
     * @param User $user
     */
    public function getWalletsDataByUser(User $user)
    {
        $query = $this->createQueryBuilder('w')
                      ->select('w')
                      ->addSelect('COALESCE(SUM(wd.amount), 0) as withdrawnAmount')
                      ->addSelect('MAX(wd.updatedAt) as lastOperationDate')
                      ->leftJoin('VifeedPaymentBundle:Withdrawal', 'wd', Join::WITH, 'wd.wallet = w AND wd.status in (:statuses)')
                      ->groupBy('w.id')
                      ->orderBy('w.type')
                      ->addOrderBy('w.id')
                      ->where('w.user = :user');

        $query->setParameter('user', $user);
        $query->setParameter('statuses', [Withdrawal::STATUS_OK]);

        return $query->getQuery()->getResult();
    }
}
