<?php

namespace Vifeed\PaymentBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Vifeed\PaymentBundle\Entity\Withdrawal;
use Vifeed\UserBundle\Entity\User;

/**
 * WithdrawalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WithdrawalRepository extends EntityRepository
{

    /**
     * @param User      $user
     * @param \DateTime $dateFrom
     * @param \DateTime $dateTo
     *
     * @return array
     */
    public function getWithdrawalStats(User $user, \DateTime $dateFrom, \DateTime $dateTo)
    {
        $qb = $this->createQueryBuilder('w');
        $query = $qb->select('w')
                    ->addSelect('i.type as type')
                    ->join('w.wallet', 'i')
                    ->where('w.user = :user')
                    ->andWhere('w.createdAt BETWEEN :date_from AND :date_to')
//                    ->andWhere('w.status = :status')
                    ->orderBy('w.createdAt');
        $query->setParameters(
              ['user'      => $user,
               'date_from' => $dateFrom,
               'date_to'   => $dateTo,
//               'status'    => Withdrawal::STATUS_OK
              ]
        );

        $payments = $query->getQuery()->getResult();

        return $payments;
    }


}
