parameters:
#    vifeed_public.example.class: Vifeed\FrontendBundle\Example

services:
#    vifeed_public.example:
#        class: %vifeed_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
