<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140221221721 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE INDEX timestamp ON video_views (timestamp)");
        $this->addSql("ALTER TABLE payment_order ADD updated_at DATETIME NOT NULL, ADD status ENUM('new', 'pending', 'paid', 'cancelled') NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE payment_order DROP updated_at, DROP status");
        $this->addSql("DROP INDEX timestamp ON video_views");
    }
}
