<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140217224652 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE campaign_ban DROP FOREIGN KEY FK_5EB434A4A76ED395");
        $this->addSql("DROP INDEX IDX_5EB434A4A76ED395 ON campaign_ban");
        $this->addSql("ALTER TABLE campaign_ban DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE campaign_ban CHANGE user_id platform_id INT NOT NULL");
        $this->addSql("ALTER TABLE campaign_ban ADD CONSTRAINT FK_5EB434A4FFE6496F FOREIGN KEY (platform_id) REFERENCES platform (id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_5EB434A4FFE6496F ON campaign_ban (platform_id)");
        $this->addSql("ALTER TABLE campaign_ban ADD PRIMARY KEY (platform_id, campaign_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE campaign_ban DROP FOREIGN KEY FK_5EB434A4FFE6496F");
        $this->addSql("DROP INDEX IDX_5EB434A4FFE6496F ON campaign_ban");
        $this->addSql("ALTER TABLE campaign_ban DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE campaign_ban CHANGE platform_id user_id INT NOT NULL");
        $this->addSql("ALTER TABLE campaign_ban ADD CONSTRAINT FK_5EB434A4A76ED395 FOREIGN KEY (user_id) REFERENCES vifeed_user (id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_5EB434A4A76ED395 ON campaign_ban (user_id)");
        $this->addSql("ALTER TABLE campaign_ban ADD PRIMARY KEY (user_id, campaign_id)");
    }
}
