services:

    vifeed.campaign.manager:
        class: Vifeed\CampaignBundle\Manager\CampaignManager
        arguments: [ @doctrine.orm.default_entity_manager, @hashids, @vifeed.tag.manager, %vifeed% ]
