angular.module 'ui.bootstrap', [
  'ui.bootstrap.pagination'
  'ui.bootstrap.dropdown'
  'ui.bootstrap.popover'
  'ui.bootstrap.tooltip'
  'ui.bootstrap.buttons'
  'ui.bootstrap.alert'
  'ui.bootstrap.tabs'
  'templates-angularUiTabs'
  'templates-angularUiTooltip'
  'templates-angularUiPopover'
  'templates-angularUiAlert'
  'templates-angularUiPagination'
  'ui.event'
  'ui.mask'
]
