sign_up:
    pattern:  /sign-up/
    defaults: { _controller: VifeedUserBundle:Frontend\User:index }
    options:
        expose: true

fos_user_registration_confirm:
    pattern: '/confirm/{token}'
    defaults:
        _controller: 'FOSUserBundle:Registration:confirm'

fos_user_registration_check_email:
    pattern: /check-email
    defaults:
        _controller: 'FOSUserBundle:Registration:checkEmail'