fos_user_registration_confirm:
    pattern: '/confirm/{token}'
    defaults:
        _controller: 'FOSUserBundle:Registration:confirm'

user_social_link:
    path: /user/social/link
    defaults:
        _controller: 'VifeedUserBundle:Social:linkUser'

fos_user_registration_check_email:
    pattern: /check-email
    defaults:
        _controller: 'FOSUserBundle:Registration:checkEmail'
