fos_user_registration_confirm:
    pattern: '/confirm/{token}'
    defaults:
        _controller: 'FOSUserBundle:Registration:confirm'

fos_user_registration_check_email:
    pattern: /check-email
    defaults:
        _controller: 'FOSUserBundle:Registration:checkEmail'

fos_user_registration_confirmed:
    pattern: /confirmed
    defaults:
        _controller: 'FOSUserBundle:Registration:confirmed'

fos_user_security_logout:
    pattern: /logout
    defaults:
        _controller: 'FOSUserBundle:Security:logout'

user_social_link:
    path: /user/social/link
    defaults:
        _controller: 'VifeedUserBundle:Social:linkUser'