services:
    wsse.security.authentication.provider:
        class:  Vifeed\UserBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", @snc_redis.default, @vifeed.user.wsse_token_manager, @logger]
        tags:
            - { name: 'monolog.logger', channel: 'auth' }

    wsse.security.authentication.listener:
        class:  Vifeed\UserBundle\Security\Firewall\WsseListener
        arguments: [ @security.context, @security.authentication.manager, @logger]
        tags:
            - { name: 'monolog.logger', channel: 'auth' }

    vifeed.security.authentication.success_handler:
        class:  Vifeed\UserBundle\EventListener\UserAuthenticationSuccessHandler
        arguments: [@vifeed.user.wsse_token_manager, @doctrine.orm.entity_manager]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    vifeed.security.authentication.failure_handler:
        class:  Vifeed\UserBundle\EventListener\UserAuthenticationFailureHandler
        tags:
            - { name: 'monolog.logger', channel: 'security' }

#    vifeed.user.registration.completed_listener:
#        class: Vifeed\UserBundle\EventListener\UserRegistrationCompletedListener
#        tags:
#            - { name: 'kernel.event_subscriber' }

    vifeed.oauth.provider.factory:
        class: Vifeed\UserBundle\OAuth\OAuthProviderFactory
        arguments: [%social%, @router]

    vifeed.user.wsse_token_manager:
        class: Vifeed\UserBundle\Manager\WsseTokenManager
        arguments: [ @snc_redis.default ]

    vifeed.user.resetting.form.type:
        class: Vifeed\UserBundle\Form\ResettingFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: resetting }

    vifeed.user.notification_manager:
        class: Vifeed\UserBundle\Manager\UserNotificationManager
        arguments: [ @vifeed.mailer, @vifeed.sms_manager, @logger ]

#    fos.user.registration.controller:
#        class:     FOS\UserBundle\Controller\RegistrationController
#        calls:
#            - [setContainer, ["@service_container"]]
    fos_user.listener.email_confirmation:
        class: Vifeed\UserBundle\EventListener\EmailConfirmationListener
        arguments: [ @vifeed.user.notification_manager, @fos_user.util.token_generator, @router, @session ]
        tags:
            - { name: 'kernel.event_subscriber' }