services:
    wsse.security.authentication.provider:
        class:  Vifeed\UserBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", "@snc_redis.default", "@vifeed.user.wsse_token_manager"]

    wsse.security.authentication.listener:
        class:  Vifeed\UserBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]

    vifeed.security.authentication.success_handler:
        class:  Vifeed\UserBundle\EventListener\UserAuthenticationSuccessHandler
        arguments: ["@vifeed.user.wsse_token_manager"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    vifeed.security.authentication.failure_handler:
        class:  Vifeed\UserBundle\EventListener\UserAuthenticationFailureHandler
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    vifeed.user.registration.completed_listener:
        class: Vifeed\UserBundle\EventListener\UserRegistrationCompletedListener
        tags:
            - { name: 'kernel.event_subscriber' }

    vifeed.oauth.provider.factory:
        class: Vifeed\UserBundle\OAuth\OAuthProviderFactory
        arguments: [%social%, '@router']

    vifeed.user.wsse_token_manager:
        class: Vifeed\UserBundle\Manager\WsseTokenManager
        arguments: ["@snc_redis.default"]

