services:
    wsse.security.authentication.provider:
        class:  Vifeed\UserBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", "@snc_redis.default"]

    wsse.security.authentication.listener:
        class:  Vifeed\UserBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]

    vifeed.security.authentication.success_handler:
        class:  Vifeed\UserBundle\EventListener\UserAuthenticationSuccessHandler
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    vifeed.security.authentication.failure_handler:
        class:  Vifeed\UserBundle\EventListener\UserAuthenticationFailureHandler
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    vifeed.oauth.provider.factory:
        class: Vifeed\UserBundle\OAuth\OAuthProviderFactory
        arguments:
            - %social%
            - '@router'